package sistemaescolar;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;

public class Exibir extends javax.swing.JFrame {

    /**
     * Creates new form Exibir
     */
    
    private Home home;
    private DefaultTableModel dt = new DefaultTableModel();
    private ArrayList<Object[]> alunos = new ArrayList<>();
    
    public Exibir() {
        initComponents();
    }
    
    public void percorreArray(){
        for(int i=0; i < alunos.size(); i++){
            dt.addRow(alunos.get(i));
        }
    }
    
    public Exibir(Home home) {
        this.home = home;
        alunos = home.getArray();
        initComponents();
        
        filtro.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
                "Filtrar", "Sala", "Aprovados", "Reprovados"}));
        
        dt = (DefaultTableModel)tabela.getModel();
        percorreArray();
    }
    
    public void forFiltro(String item){
        for(int i=0; i < alunos.size(); i++){
            Object[] aluno = alunos.get(i);
            
            if(aluno[6].equals(item.substring(0, item.length()-1))){
                dt.addRow(aluno);
            }
        }
    }
    
    public void forSala(String sala){
        int cont=0;
        
        for(int i=0; i < alunos.size(); i++){
            Object[] aluno = alunos.get(i);
            
            if(aluno[1].equals(sala)){
                dt.addRow(aluno);
                cont++;
            }
        }
        
        if(cont == 0){
            JOptionPane.showMessageDialog(rootPane, "Sala não adicionada.");
            percorreArray();
        }
    }
    
    public void removeAluno(String nome){
        for(int i=0; i < alunos.size(); i++){
            Object[] aluno = alunos.get(i);

            if(aluno[0].equals(nome)){
                dt.removeRow(i);
                alunos.remove(i);
            }
        }
    }
    
    public Boolean existeAluno(String nome){
        for(int i=0; i < alunos.size(); i++){
            Object[] aluno = alunos.get(i);

            if(aluno[0].equals(nome)){
                return true;
            }
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtro = new javax.swing.JComboBox<>();
        btnRemover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filtro.setToolTipText("FIltro");
        filtro.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                filtroComponentAdded(evt);
            }
        });
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });
        getContentPane().add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, -1, -1));

        jButton1.setText("← Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 48, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Exibir alunos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 200, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 1000, 10));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno", "Sala", "Nota 1", "Nota 2", " Nota 3", " Nota 4", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 790, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgroundimagetabela.jpeg"))); // NOI18N
        jLabel1.setText("Filtro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        home.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        String item = (String) filtro.getSelectedItem();
        
        //Enquanto existir uma linha
        while (dt.getRowCount() > 0) {
            dt.removeRow(0);
        }
        
        switch (item) {
            case "Aprovados" -> forFiltro(item);
            case "Reprovados" -> forFiltro(item);
            case "Sala" -> {
                String sala = JOptionPane.showInputDialog("Insira a sala: ");
                forSala(sala);
            }
            case "Filtrar" -> percorreArray();
        }
    }//GEN-LAST:event_filtroActionPerformed

    private void filtroComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_filtroComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroComponentAdded

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        String nomeApagar = JOptionPane.showInputDialog(rootPane, "Nome que deseja apagar: ");
        Boolean resul = existeAluno(nomeApagar);
        
        
        if(resul == true){
            int decisao = JOptionPane.showConfirmDialog(rootPane, "Deseja mesmo apagar o aluno " + nomeApagar + "?");

            if(decisao == 0){
                removeAluno(nomeApagar);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nome não cadastrado.");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //GuardaAluno aluno = new GuardaAluno();
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exibir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
